package com.distractors.generation.systemsOfTwoEquations;

public record SystemOfTwoEquationsDistractors(SystemOfTwoEquationsSolution correctSolution, SystemOfTwoEquationsSolution distractor_1, SystemOfTwoEquationsSolution distractor_2, SystemOfTwoEquationsSolution distractor_3) {

}
