package com.distractors.generation.quadraticInequalities;

public record QuadraticInequalityDistractors(QuadraticInequalitySolution correctSolution, QuadraticInequalitySolution distractor_1, QuadraticInequalitySolution distractor_2, QuadraticInequalitySolution distractor_3) {

}
